---

# tasks file for install zookeeper on centos


- name: check if jdk is installed
  shell: java -version 2>&1
  register: jdk_installed
  ignore_errors: true

- name: install openjdk if jdk is not installed
  yum: name=java-1.8.0-openjdk state=present
  when: jdk_installed | failed

- name: create cdh5 yum repo
  copy: src=cloudera-cdh5.repo dest=/etc/yum.repos.d/cloudera-cdh5.repo

- name: install zookeeper
  yum: name={{ item }} state=present enablerepo=cloudera-cdh5
  with_items:
    - zookeeper
    - zookeeper-server

- name: config zookeeper
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
            owner=zookeeper group=zookeeper backup=yes
  notify: restart zookeeper

- name: set myid
  shell: sudo su -s /bin/bash zookeeper -c " zookeeper-server-initialize  --force --myid={{ zk_myid }}"

- name: start and enable zookeeper server
  service: name=zookeeper-server enabled=yes state=started

